DELETE FROM CF_API_INFO WHERE api_code ='CFS_YD_YYJR_ADD';
DELETE FROM CF_API_INFO WHERE api_code ='RFS_4G_SJ_GJMY';
DELETE FROM CF_API_INFO WHERE api_code ='RES-2G_HXWYY_C';
DELETE FROM CF_API_INFO WHERE api_code ='RES-2G_HXWYY_C';
